services:
  # Cloud service - handles its own SDK building
  cloud:
    stop_grace_period: 10s
    init: true
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          memory: 256M
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "8002:80"
    environment:
      - HOST=0.0.0.0
      - SERVICE_NAME=cloud
      - CONTAINER_ENVIRONMENT=true
      - CLOUD_HOST_NAME=cloud
      - LIVEKIT_GRPC_SOCKET=/var/run/livekit/bridge.sock
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - bun_cache:/root/.bun
      - livekit_socket:/var/run/livekit
    command: bash -c "bun install && cd packages/sdk && bun run build && cd ../cloud && bun install && bun run dev"
    tty: true
    stdin_open: true
    depends_on:
      - livekit-bridge

  # LiveKit gRPC Bridge service
  livekit-bridge:
    build:
      context: ./packages/cloud-livekit-bridge
      dockerfile: Dockerfile
    environment:
      - PORT=9090
      - LOG_LEVEL=debug
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - LIVEKIT_GRPC_SOCKET=/var/run/livekit/bridge.sock
    volumes:
      - livekit_socket:/var/run/livekit
    restart: "no"
    healthcheck:
      test: ["CMD", "test", "-S", "/var/run/livekit/bridge.sock"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  node_modules:
  bun_cache:
  livekit_socket:
