services:
  # Cloud service - handles its own SDK building
  cloud:
    stop_grace_period: 10s
    init: true
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          memory: 256M
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "8002:80"
    environment:
      - HOST=0.0.0.0
      - SERVICE_NAME=cloud
      - CONTAINER_ENVIRONMENT=true
      - CLOUD_HOST_NAME=cloud
      - LIVEKIT_GO_BRIDGE_URL=ws://livekit-bridge:8080
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - bun_cache:/root/.bun
    command: bash -c "bun install && cd packages/sdk && bun run build && cd ../cloud && bun install && bun run dev"
    tty: true
    stdin_open: true
    depends_on:
      - livekit-bridge

  # LiveKit Go Bridge service
  livekit-bridge:
    build:
      context: ./livekit-client-2
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - LOG_LEVEL=debug
      - LIVEKIT_URL=${LIVEKIT_URL}
    restart: "no"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  node_modules:
  bun_cache:
