apiVersion: v1
kind: Service
metadata:
  name: cloud-debug-udp
  namespace: default
  labels:
    porter.run/app-name: cloud-debug
spec:
  type: LoadBalancer
  selector:
    porter.run/app-name: cloud-debug
    porter.run/service-name: cloud
  ports:
    - name: udp-audio
      protocol: UDP
      port: 8000
      targetPort: 8000
