export interface Language {
  code: string
  name: string
}

export const AVAILABLE_LANGUAGES: Language[] = [
  { code: "af-ZA", name: "Afrikaans" },
  { code: "am-ET", name: "Amharic" },
  { code: "ar-AE", name: "Arabic (UAE)" },
  { code: "ar-BH", name: "Arabic (Bahrain)" },
  { code: "ar-DZ", name: "Arabic (Algeria)" },
  { code: "ar-EG", name: "Arabic (Egypt)" },
  { code: "ar-IL", name: "Arabic (Israel)" },
  { code: "ar-IQ", name: "Arabic (Iraq)" },
  { code: "ar-JO", name: "Arabic (Jordan)" },
  { code: "ar-KW", name: "Arabic (Kuwait)" },
  { code: "ar-LB", name: "Arabic (Lebanon)" },
  { code: "ar-LY", name: "Arabic (Libya)" },
  { code: "ar-MA", name: "Arabic (Morocco)" },
  { code: "ar-OM", name: "Arabic (Oman)" },
  { code: "ar-PS", name: "Arabic (Palestine)" },
  { code: "ar-QA", name: "Arabic (Qatar)" },
  { code: "ar-SA", name: "Arabic (Saudi Arabia)" },
  { code: "ar-SY", name: "Arabic (Syria)" },
  { code: "ar-TN", name: "Arabic (Tunisia)" },
  { code: "ar-YE", name: "Arabic (Yemen)" },
  { code: "as-IN", name: "Assamese" },
  { code: "az-AZ", name: "Azerbaijani" },
  { code: "bg-BG", name: "Bulgarian" },
  { code: "bn-IN", name: "Bengali" },
  { code: "bs-BA", name: "Bosnian" },
  { code: "ca-ES", name: "Catalan" },
  { code: "cs-CZ", name: "Czech" },
  { code: "cy-GB", name: "Welsh" },
  { code: "da-DK", name: "Danish" },
  { code: "de-AT", name: "German (Austria)" },
  { code: "de-CH", name: "German (Switzerland)" },
  { code: "de-DE", name: "German" },
  { code: "el-GR", name: "Greek" },
  { code: "en-AU", name: "English (Australia)" },
  { code: "en-CA", name: "English (Canada)" },
  { code: "en-GB", name: "English (UK)" },
  { code: "en-GH", name: "English (Ghana)" },
  { code: "en-HK", name: "English (Hong Kong)" },
  { code: "en-IE", name: "English (Ireland)" },
  { code: "en-IN", name: "English (India)" },
  { code: "en-KE", name: "English (Kenya)" },
  { code: "en-NG", name: "English (Nigeria)" },
  { code: "en-NZ", name: "English (New Zealand)" },
  { code: "en-PH", name: "English (Philippines)" },
  { code: "en-SG", name: "English (Singapore)" },
  { code: "en-TZ", name: "English (Tanzania)" },
  { code: "en-US", name: "English (US)" },
  { code: "en-ZA", name: "English (South Africa)" },
  { code: "es-AR", name: "Spanish (Argentina)" },
  { code: "es-BO", name: "Spanish (Bolivia)" },
  { code: "es-CL", name: "Spanish (Chile)" },
  { code: "es-CO", name: "Spanish (Colombia)" },
  { code: "es-CR", name: "Spanish (Costa Rica)" },
  { code: "es-CU", name: "Spanish (Cuba)" },
  { code: "es-DO", name: "Spanish (Dominican Republic)" },
  { code: "es-EC", name: "Spanish (Ecuador)" },
  { code: "es-ES", name: "Spanish (Spain)" },
  { code: "es-GQ", name: "Spanish (Equatorial Guinea)" },
  { code: "es-GT", name: "Spanish (Guatemala)" },
  { code: "es-HN", name: "Spanish (Honduras)" },
  { code: "es-MX", name: "Spanish (Mexico)" },
  { code: "es-NI", name: "Spanish (Nicaragua)" },
  { code: "es-PA", name: "Spanish (Panama)" },
  { code: "es-PE", name: "Spanish (Peru)" },
  { code: "es-PR", name: "Spanish (Puerto Rico)" },
  { code: "es-PY", name: "Spanish (Paraguay)" },
  { code: "es-SV", name: "Spanish (El Salvador)" },
  { code: "es-US", name: "Spanish (US)" },
  { code: "es-UY", name: "Spanish (Uruguay)" },
  { code: "es-VE", name: "Spanish (Venezuela)" },
  { code: "et-EE", name: "Estonian" },
  { code: "eu-ES", name: "Basque" },
  { code: "fa-IR", name: "Persian" },
  { code: "fi-FI", name: "Finnish" },
  { code: "fil-PH", name: "Filipino" },
  { code: "fr-BE", name: "French (Belgium)" },
  { code: "fr-CA", name: "French (Canada)" },
  { code: "fr-CH", name: "French (Switzerland)" },
  { code: "fr-FR", name: "French" },
  { code: "ga-IE", name: "Irish" },
  { code: "gl-ES", name: "Galician" },
  { code: "gu-IN", name: "Gujarati" },
  { code: "ha-NG", name: "Hausa" },
  { code: "he-IL", name: "Hebrew" },
  { code: "hi-IN", name: "Hindi" },
  { code: "hr-HR", name: "Croatian" },
  { code: "hu-HU", name: "Hungarian" },
  { code: "hy-AM", name: "Armenian" },
  { code: "id-ID", name: "Indonesian" },
  { code: "ig-NG", name: "Igbo" },
  { code: "is-IS", name: "Icelandic" },
  { code: "it-CH", name: "Italian (Switzerland)" },
  { code: "it-IT", name: "Italian" },
  { code: "ja-JP", name: "Japanese" },
  { code: "jv-ID", name: "Javanese" },
  { code: "ka-GE", name: "Georgian" },
  { code: "kk-KZ", name: "Kazakh" },
  { code: "km-KH", name: "Khmer" },
  { code: "kn-IN", name: "Kannada" },
  { code: "ko-KR", name: "Korean" },
  { code: "lo-LA", name: "Lao" },
  { code: "lt-LT", name: "Lithuanian" },
  { code: "lv-LV", name: "Latvian" },
  { code: "mk-MK", name: "Macedonian" },
  { code: "ml-IN", name: "Malayalam" },
  { code: "mn-MN", name: "Mongolian" },
  { code: "mr-IN", name: "Marathi" },
  { code: "ms-MY", name: "Malay" },
  { code: "mt-MT", name: "Maltese" },
  { code: "my-MM", name: "Burmese" },
  { code: "nb-NO", name: "Norwegian Bokmål" },
  { code: "ne-NP", name: "Nepali" },
  { code: "nl-BE", name: "Dutch (Belgium)" },
  { code: "nl-NL", name: "Dutch" },
  { code: "or-IN", name: "Odia" },
  { code: "pa-IN", name: "Punjabi" },
  { code: "pl-PL", name: "Polish" },
  { code: "ps-AF", name: "Pashto" },
  { code: "pt-BR", name: "Portuguese (Brazil)" },
  { code: "pt-PT", name: "Portuguese (Portugal)" },
  { code: "ro-RO", name: "Romanian" },
  { code: "ru-RU", name: "Russian" },
  { code: "si-LK", name: "Sinhala" },
  { code: "sk-SK", name: "Slovak" },
  { code: "sl-SI", name: "Slovenian" },
  { code: "so-SO", name: "Somali" },
  { code: "sq-AL", name: "Albanian" },
  { code: "sr-RS", name: "Serbian" },
  { code: "sv-SE", name: "Swedish" },
  { code: "sw-KE", name: "Swahili (Kenya)" },
  { code: "sw-TZ", name: "Swahili (Tanzania)" },
  { code: "ta-IN", name: "Tamil" },
  { code: "te-IN", name: "Telugu" },
  { code: "th-TH", name: "Thai" },
  { code: "tr-TR", name: "Turkish" },
  { code: "uk-UA", name: "Ukrainian" },
  { code: "ur-IN", name: "Urdu" },
  { code: "uz-UZ", name: "Uzbek" },
  { code: "vi-VN", name: "Vietnamese" },
  { code: "wuu-CN", name: "Chinese (Wu)" },
  { code: "yo-NG", name: "Yoruba" },
  { code: "yue-CN", name: "Chinese (Cantonese, Simplified)" },
  { code: "zh-CN", name: "Chinese (Mandarin, Simplified)" },
  { code: "zh-CN-shandong", name: "Chinese (Jilu Mandarin)" },
  { code: "zh-CN-sichuan", name: "Chinese (Southwestern Mandarin)" },
  { code: "zh-HK", name: "Chinese (Cantonese, Traditional)" },
  { code: "zh-TW", name: "Chinese (Taiwanese Mandarin)" },
  { code: "zu-ZA", name: "Zulu" },
]

export function getLanguageName(code: string): string {
  return AVAILABLE_LANGUAGES.find((l) => l.code === code)?.name || code
}

export function searchLanguages(query: string): Language[] {
  const lowerQuery = query.toLowerCase()
  return AVAILABLE_LANGUAGES.filter(
    (l) => l.name.toLowerCase().includes(lowerQuery) || l.code.toLowerCase().includes(lowerQuery),
  )
}

export function getAvailableHints(primaryLanguage: string): Language[] {
  // Return all languages except the primary language for use as hints
  return AVAILABLE_LANGUAGES.filter((l) => l.code !== primaryLanguage)
}

export function getFlagEmoji(countryCode: string): string {
  const codePoints = countryCode
    .toUpperCase()
    .split("-")
    .pop()!
    .split("")
    .map((char) => 127397 + char.charCodeAt(0))
  return String.fromCodePoint(...codePoints)
}
