version: '3.8'

services:
  rtmp-relay:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1935:1935"    # RTMP port
      - "9997:9997"    # API port for health checks
    env_file:
      - .env
    environment:
      - CLOUD_API_URL=${CLOUD_API_URL:-https://api.mentra.glass}
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"