# Porter configuration for RTMP relay service
version: v2

services:
  - name: rtmp-relay-uscentral
    type: web
    
    # Build configuration
    build:
      method: docker
      context: ./
      dockerfile: ./Dockerfile
    
    # Resource allocation
    cpu:
      request: 0.5
      limit: 2
    memory:
      request: 512Mi
      limit: 1Gi
    
    # Networking
    ports:
      - port: 1935
        protocol: TCP
        expose_to_external: true  # Glasses need to reach this
      - port: 9997
        protocol: TCP
        expose_to_external: false # Internal health checks only
    
    # Environment variables
    env:
      - name: CLOUD_API_URL
        value: "https://api.mentra.glass"
      - name: RTMP_PATH_USER
        value: "$1"  # MediaMTX provides path segments
      - name: RTMP_PATH_NAME
        value: "$2"
      - name: RTMP_PATH
        value: "$RTMP_PATH"  # Full path from MediaMTX
    
    # Health check
    healthCheck:
      path: /v3/config/get
      port: 9997
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    
    # Scaling
    replicas: 1
    autoscaling:
      enabled: false  # Enable later when needed
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 70