version: '3.8'

services:
  livekit-bridge:
    build: .
    ports:
      - "8081:8080"
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL:-wss://livekit.example.com}
      - PORT=8080
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped