# Maestro Configuration for MentraOS

# Global test configuration
appId: com.mentra.mentra
name: "MentraOS E2E Tests"

# Test tags for organizing test runs
tags:
  - mobile
  - react-native
  - mentraos

# Global environment variables
env:
  MAESTRO_APP_ID: com.mentra.mentra

# Flows to include in test suite
# Comment out flows to exclude them from runs
includedFlows:
  - flows/01-auth-flow.yaml
  - flows/02-tab-navigation.yaml
  - flows/03-app-store.yaml
  - flows/04-simulated-glasses-pairing.yaml
  - flows/05-no-internet-connection.yaml
  - flows/06-launch-app-simulated-glasses.yaml

# Global flow configuration
flowConfig:
  # How long to wait for elements before timing out (ms)
  defaultTimeout: 10000

  # Take screenshots on failure
  screenshotOnFailure: true

  # Video recording
  recordVideo: false

  # Continue on failure
  continueOnFailure: false
