services:
  # this new service will run first. it installs dependencies and builds the shared packages
  # that other services like 'cloud' and 'dashboard-manager' need to run.
  builder:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - bun_cache:/root/.bun
    # this command installs everything and then builds the shared packages one by one
    # command: >
    #   bash -c "bun install && 
    #   cd packages/sdk && bun run build" 

  # Cloud service
  cloud:
    stop_grace_period: 10s
    init: true
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          memory: 256M
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8002:80"
    environment:
      - HOST=0.0.0.0
      - SERVICE_NAME=cloud
      - CONTAINER_ENVIRONMENT=true
      - CLOUD_HOST_NAME=cloud
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - bun_cache:/root/.bun
    command: bash -c "cd packages/cloud && bun install && bun run dev"
    # networks:
    #   - augmentos-network-dev
    depends_on:
      builder:
        condition: service_completed_successfully

# networks:
#   augmentos-network-dev:
#     driver: bridge
#     external: true
#     name: augmentos-network-dev

volumes:
  node_modules:
  bun_cache: