name: Test AugmentOS Cloud PR (dev → main)

on:
  pull_request:
    types: [synchronize]
    branches:
      - main
      - dev # remove after testing

jobs:
  test_live_captions:
    if: ${{ (github.head_ref == 'dev' && github.base_ref == 'main') || github.base_ref == 'dev' }}
    # change to github.head_ref == 'dev' && github.base_ref == 'main' after testing
    name: Cloud Client Live Captions (dev -> main)
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
      DEFAULT_SERVER_URL: https://devapi.mentra.glass:443
      AUGMENTOS_AUTH_JWT_SECRET: ${{ secrets.AUGMENTOS_AUTH_JWT_SECRET }}
      JOE_MAMA_USER_JWT: ${{ secrets.JOE_MAMA_USER_JWT }}
      SYSTEM_DASHBOARD_PACKAGE_NAME: ${{ vars.SYSTEM_DASHBOARD_PACKAGE_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION || 'latest' }}

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('cloud/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install Dependencies
        working-directory: cloud
        run: bun run setup-deps

      - name: Build all projects
        working-directory: cloud
        run: bun run build

      - name: Run live captions tests
        working-directory: cloud/cloud-client
        run: bun run test:live-captions
