name: MentraOS Manager iOS Build

on:
  pull_request:
    paths:
      - 'augmentos_manager/**'
      - '.github/workflows/mentraos-manager-ios-build.yml'
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: augmentos_manager/package.json

      - name: Install dependencies
        working-directory: ./augmentos_manager
        run: pnpm install --no-frozen-lockfile

      - name: Run Expo prebuild
        working-directory: ./augmentos_manager
        run: pnpm expo prebuild --platform ios

      - name: Install CocoaPods dependencies
        working-directory: ./augmentos_manager/ios
        run: pod install

      - name: Build iOS app for Simulator
        working-directory: ./augmentos_manager/ios
        run: |
          xcodebuild -workspace AOS.xcworkspace \
                     -scheme AOS \
                     -configuration Debug \
                     -sdk iphonesimulator \
                     -derivedDataPath build \
                     -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'

      - name: Build iOS app for Device
        working-directory: ./augmentos_manager/ios
        run: |
          xcodebuild -workspace AOS.xcworkspace \
                     -scheme AOS \
                     -configuration Release \
                     -sdk iphoneos \
                     -derivedDataPath build-device \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO

      - name: Upload Simulator Build
        uses: actions/upload-artifact@v3
        with:
          name: ios-simulator-build
          path: augmentos_manager/ios/build/Build/Products/Debug-iphonesimulator/AOS.app

      - name: Upload Device Build
        uses: actions/upload-artifact@v3
        with:
          name: ios-device-build
          path: augmentos_manager/ios/build-device/Build/Products/Release-iphoneos/AOS.app